/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buyukrisk;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.util.logging.PlatformLogger.Level;


/**
 *
 * @author TOSHIBA S70
 */
public class Anaekran extends javax.swing.JFrame {

    /**
     * Creates new form Anaekran
     */
    public Anaekran() {
      
        initComponents();
        setSize(1200,650);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resimPaneli2 = new buyukrisk.ResimPaneli();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        resimPaneli2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("3.Yarışmacı:");
        jLabel1.setToolTipText("");
        resimPaneli2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1.Yarışmacı:");
        resimPaneli2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, 22));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("2.Yarışmacı:");
        resimPaneli2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, 20));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 255));
        resimPaneli2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 260, 40));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 255));
        resimPaneli2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 260, 40));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 255));
        resimPaneli2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 260, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("BAŞLA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        resimPaneli2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 200, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resimPaneli2, javax.swing.GroupLayout.DEFAULT_SIZE, 1155, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resimPaneli2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if (jTextField1.getText(). equals("") || jTextField2.getText().equals("") || jTextField3.getText().equals("") )
        {    
        
            JOptionPane.showMessageDialog(null,"Text Alanları Boş Bırakılamaz");
        }
        else
        {
        
         try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = null;
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/briskveritabani", "root", "123456");
            
            Statement sta =  (Statement) conn.createStatement();
            
            String komut = "INSERT INTO yarismacilar(KisiID,Ad,Puan) VALUES (1,'" + jTextField1.getText() + "', 0)";
            String komut2 = "INSERT INTO yarismacilar(KisiID,Ad,Puan) VALUES (2,'" + jTextField2.getText() + "', 0)";
            String komut3 = "INSERT INTO yarismacilar(KisiID,Ad,Puan) VALUES (3,'" + jTextField3.getText() + "', 0)";
            
            sta.execute(komut);
            sta.execute(komut2);
            sta.execute(komut3);
            conn.close();
            
              Etap1 frm2 = new Etap1();
              frm2.setVisible(true);
              this.hide();
        
            
        } catch (ClassNotFoundException ex) {
           System.out.println("Sınıf bulunamadı");
            
        } catch (SQLException e) {
            System.out.println("Veritabanı bulunamadı");
        }
         
            
         
        
        
      
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anaekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anaekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anaekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anaekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anaekran().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    private buyukrisk.ResimPaneli resimPaneli2;
    // End of variables declaration//GEN-END:variables
}
