/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buyukrisk;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author TOSHIBA S70
 */
public class Etap1 extends javax.swing.JFrame {

    /**
     * Creates new form Etap1
     */
    public Etap1() {
        initComponents();
        setLocationRelativeTo(null); 
       
        
        try
        {
         st = baglantiAc();
         veri = st.executeQuery("SELECT Ad FROM yarismacilar");
         veri.next();
         isim1.setText(veri.getString(1));
         veri.next();
         isim2.setText(veri.getString(1));
         veri.next();
         isim3.setText(veri.getString(1));
         
        
        
        
        }catch(Exception e){
            System.out.println("Veitabanı bağlantı hatası");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resimPaneli21 = new buyukrisk.ResimPaneli2();
        isim3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buton25 = new javax.swing.JButton();
        buton11 = new javax.swing.JButton();
        buton12 = new javax.swing.JButton();
        buton13 = new javax.swing.JButton();
        buton14 = new javax.swing.JButton();
        buton15 = new javax.swing.JButton();
        buton55 = new javax.swing.JButton();
        buton22 = new javax.swing.JButton();
        buton23 = new javax.swing.JButton();
        buton24 = new javax.swing.JButton();
        buton21 = new javax.swing.JButton();
        buton31 = new javax.swing.JButton();
        buton32 = new javax.swing.JButton();
        buton33 = new javax.swing.JButton();
        buton34 = new javax.swing.JButton();
        buton35 = new javax.swing.JButton();
        buton41 = new javax.swing.JButton();
        buton42 = new javax.swing.JButton();
        buton43 = new javax.swing.JButton();
        buton44 = new javax.swing.JButton();
        buton45 = new javax.swing.JButton();
        buton51 = new javax.swing.JButton();
        buton52 = new javax.swing.JButton();
        buton53 = new javax.swing.JButton();
        buton54 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sorulabel = new javax.swing.JLabel();
        zamanlabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        isim2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        puan3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cevap3 = new javax.swing.JTextField();
        cevap1 = new javax.swing.JTextField();
        cevap2 = new javax.swing.JTextField();
        cevapla3 = new javax.swing.JButton();
        cevapla1 = new javax.swing.JButton();
        cevapla2 = new javax.swing.JButton();
        isim1 = new javax.swing.JLabel();
        puan1 = new javax.swing.JLabel();
        puan2 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        resimPaneli21.setFocusable(true);
        resimPaneli21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resimPaneli21KeyPressed(evt);
            }
        });
        resimPaneli21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isim3.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        isim3.setForeground(new java.awt.Color(0, 0, 153));
        isim3.setText("3.Yarışmacı");
        resimPaneli21.add(isim3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 600, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("________");
        resimPaneli21.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 40, 220, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("ŞEHİRLER");
        resimPaneli21.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("_____________");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        resimPaneli21.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 630, 340, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("BAŞI SONU N");
        resimPaneli21.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("________");
        resimPaneli21.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 220, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("________");
        resimPaneli21.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 220, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("BALTASI VAR");
        resimPaneli21.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("________");
        resimPaneli21.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 220, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("KULAK");
        resimPaneli21.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, -1, -1));

        buton25.setBackground(new java.awt.Color(255, 102, 0));
        buton25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton25.setForeground(new java.awt.Color(255, 255, 255));
        buton25.setText("500");
        buton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton25ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 130, 50));

        buton11.setBackground(new java.awt.Color(255, 102, 0));
        buton11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton11.setForeground(new java.awt.Color(255, 255, 255));
        buton11.setText("100");
        buton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton11ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 130, 50));

        buton12.setBackground(new java.awt.Color(255, 102, 0));
        buton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton12.setForeground(new java.awt.Color(255, 255, 255));
        buton12.setText("200");
        buton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton12ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, 50));

        buton13.setBackground(new java.awt.Color(255, 102, 0));
        buton13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton13.setForeground(new java.awt.Color(255, 255, 255));
        buton13.setText("300");
        buton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton13ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 130, 50));

        buton14.setBackground(new java.awt.Color(255, 102, 0));
        buton14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton14.setForeground(new java.awt.Color(255, 255, 255));
        buton14.setText("400");
        buton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton14ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 130, 50));

        buton15.setBackground(new java.awt.Color(255, 102, 0));
        buton15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton15.setForeground(new java.awt.Color(255, 255, 255));
        buton15.setText("500");
        buton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton15ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 130, 50));

        buton55.setBackground(new java.awt.Color(255, 102, 0));
        buton55.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton55.setForeground(new java.awt.Color(255, 255, 255));
        buton55.setText("500");
        buton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton55ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 380, 130, 50));

        buton22.setBackground(new java.awt.Color(255, 102, 0));
        buton22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton22.setForeground(new java.awt.Color(255, 255, 255));
        buton22.setText("200");
        buton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton22ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 130, 50));

        buton23.setBackground(new java.awt.Color(255, 102, 0));
        buton23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton23.setForeground(new java.awt.Color(255, 255, 255));
        buton23.setText("300");
        buton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton23ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 130, 50));

        buton24.setBackground(new java.awt.Color(255, 102, 0));
        buton24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton24.setForeground(new java.awt.Color(255, 255, 255));
        buton24.setText("400");
        buton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton24ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 130, 50));

        buton21.setBackground(new java.awt.Color(255, 102, 0));
        buton21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton21.setForeground(new java.awt.Color(255, 255, 255));
        buton21.setText("100");
        buton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton21ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 130, 50));

        buton31.setBackground(new java.awt.Color(255, 102, 0));
        buton31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton31.setForeground(new java.awt.Color(255, 255, 255));
        buton31.setText("100");
        buton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton31ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 130, 50));

        buton32.setBackground(new java.awt.Color(255, 102, 0));
        buton32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton32.setForeground(new java.awt.Color(255, 255, 255));
        buton32.setText("200");
        buton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton32ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 130, 50));

        buton33.setBackground(new java.awt.Color(255, 102, 0));
        buton33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton33.setForeground(new java.awt.Color(255, 255, 255));
        buton33.setText("300");
        buton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton33ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 130, 50));

        buton34.setBackground(new java.awt.Color(255, 102, 0));
        buton34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton34.setForeground(new java.awt.Color(255, 255, 255));
        buton34.setText("400");
        buton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton34ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 130, 50));

        buton35.setBackground(new java.awt.Color(255, 102, 0));
        buton35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton35.setForeground(new java.awt.Color(255, 255, 255));
        buton35.setText("500");
        buton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton35ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 130, 50));

        buton41.setBackground(new java.awt.Color(255, 102, 0));
        buton41.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton41.setForeground(new java.awt.Color(255, 255, 255));
        buton41.setText("100");
        buton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton41ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 130, 50));

        buton42.setBackground(new java.awt.Color(255, 102, 0));
        buton42.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton42.setForeground(new java.awt.Color(255, 255, 255));
        buton42.setText("200");
        buton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton42ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 130, 50));

        buton43.setBackground(new java.awt.Color(255, 102, 0));
        buton43.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton43.setForeground(new java.awt.Color(255, 255, 255));
        buton43.setText("300");
        buton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton43ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 130, 50));

        buton44.setBackground(new java.awt.Color(255, 102, 0));
        buton44.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton44.setForeground(new java.awt.Color(255, 255, 255));
        buton44.setText("400");
        buton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton44ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 130, 50));

        buton45.setBackground(new java.awt.Color(255, 102, 0));
        buton45.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton45.setForeground(new java.awt.Color(255, 255, 255));
        buton45.setText("500");
        buton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton45ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 130, 50));

        buton51.setBackground(new java.awt.Color(255, 102, 0));
        buton51.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton51.setForeground(new java.awt.Color(255, 255, 255));
        buton51.setText("100");
        buton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton51ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 100, 130, 50));

        buton52.setBackground(new java.awt.Color(255, 102, 0));
        buton52.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton52.setForeground(new java.awt.Color(255, 255, 255));
        buton52.setText("200");
        buton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton52ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 170, 130, 50));

        buton53.setBackground(new java.awt.Color(255, 102, 0));
        buton53.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton53.setForeground(new java.awt.Color(255, 255, 255));
        buton53.setText("300");
        buton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton53ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 240, 130, 50));

        buton54.setBackground(new java.awt.Color(255, 102, 0));
        buton54.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buton54.setForeground(new java.awt.Color(255, 255, 255));
        buton54.setText("400");
        buton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton54ActionPerformed(evt);
            }
        });
        resimPaneli21.add(buton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 310, 130, 50));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("----------------------------------------------------------------SORU----------------------------------------------------------------");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1100, -1));

        sorulabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sorulabel.setForeground(new java.awt.Color(255, 255, 255));
        sorulabel.setText("Tablodan bir soru seçin");
        jPanel1.add(sorulabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        zamanlabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        zamanlabel.setForeground(new java.awt.Color(255, 102, 0));
        zamanlabel.setText("Kalan Süre:");
        jPanel1.add(zamanlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        resimPaneli21.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 1210, 90));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("SİVRİDİR");
        resimPaneli21.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("________");
        resimPaneli21.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 220, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("Cevap:");
        resimPaneli21.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 650, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("_____________");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        resimPaneli21.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, 300, 10));

        isim2.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        isim2.setForeground(new java.awt.Color(0, 0, 153));
        isim2.setText("2.Yarışmacı");
        resimPaneli21.add(isim2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, -1, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("____________\n");
        jLabel18.setToolTipText("");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        resimPaneli21.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, 290, 10));

        puan3.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        puan3.setForeground(new java.awt.Color(255, 255, 255));
        puan3.setText("PUAN:0");
        resimPaneli21.add(puan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 600, 220, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 0));
        jLabel20.setText("Cevap:");
        resimPaneli21.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, -1, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 0));
        jLabel21.setText("Cevap:");
        resimPaneli21.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 650, -1, 30));

        cevap3.setBackground(new java.awt.Color(0, 255, 255));
        cevap3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cevap3.setEnabled(false);
        resimPaneli21.add(cevap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 650, 290, 40));

        cevap1.setBackground(new java.awt.Color(0, 255, 255));
        cevap1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cevap1.setEnabled(false);
        resimPaneli21.add(cevap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, 290, 40));

        cevap2.setBackground(new java.awt.Color(0, 255, 255));
        cevap2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cevap2.setEnabled(false);
        resimPaneli21.add(cevap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 650, 290, 40));

        cevapla3.setBackground(new java.awt.Color(255, 102, 0));
        cevapla3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cevapla3.setForeground(new java.awt.Color(255, 255, 255));
        cevapla3.setText("CEVAPLA");
        cevapla3.setEnabled(false);
        cevapla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cevapla3ActionPerformed(evt);
            }
        });
        resimPaneli21.add(cevapla3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 710, 250, 50));

        cevapla1.setBackground(new java.awt.Color(255, 102, 0));
        cevapla1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cevapla1.setForeground(new java.awt.Color(255, 255, 255));
        cevapla1.setText("CEVAPLA");
        cevapla1.setEnabled(false);
        cevapla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cevapla1ActionPerformed(evt);
            }
        });
        resimPaneli21.add(cevapla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 710, 250, 50));

        cevapla2.setBackground(new java.awt.Color(255, 102, 0));
        cevapla2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cevapla2.setForeground(new java.awt.Color(255, 255, 255));
        cevapla2.setText("CEVAPLA");
        cevapla2.setEnabled(false);
        cevapla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cevapla2ActionPerformed(evt);
            }
        });
        resimPaneli21.add(cevapla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 710, 250, 50));

        isim1.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        isim1.setForeground(new java.awt.Color(0, 0, 153));
        isim1.setText("1.Yarışmacı");
        resimPaneli21.add(isim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 140, 30));

        puan1.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        puan1.setForeground(new java.awt.Color(255, 255, 255));
        puan1.setText("PUAN:0");
        resimPaneli21.add(puan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 600, 260, 30));

        puan2.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        puan2.setForeground(new java.awt.Color(255, 255, 255));
        puan2.setText("PUAN:0");
        resimPaneli21.add(puan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, 250, 30));

        panel2.setBackground(new java.awt.Color(255, 0, 0));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 204));
        jLabel26.setText("2");
        panel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        resimPaneli21.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 50, 50));

        panel1.setBackground(new java.awt.Color(255, 0, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 204));
        jLabel25.setText("1");
        panel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 20, -1));

        resimPaneli21.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 50, 50));

        panel3.setBackground(new java.awt.Color(255, 0, 0));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 51, 204));
        jLabel27.setText("3");
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        resimPaneli21.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 550, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resimPaneli21, javax.swing.GroupLayout.DEFAULT_SIZE, 1489, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resimPaneli21, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Connection conn = null;
    ResultSet veri;
    Statement st;
    boolean key1basildimi,key2basildimi,key3basildimi,key1ilkmi,key2ilkmi,key3ilkmi,sorusecildimi = false;
    int sayac_baslangic = 15,okunan_soru_sayisi = 0,basilanbuton;
    int sayac = 15, hatali_cevap_sayisi = 0,puan = 0;//sayac_yarismacicevap = 0;
    String cevap,soru_sececek_yarismaci;
    private char keyChar = 'A';
    
    
   
    
    Timer zamanlayici = new Timer(1000, new ActionListener(){
            
               @Override
                public void actionPerformed(ActionEvent e)
                {
                  sayac = sayac - 1;
                  zamanlabel.setText(" Kalan Süre: " + Integer.toString(sayac));
                  
                  if ( sayac == 0)
                  { 
                          cevap1.setEnabled(false);
                          cevapla1.setEnabled(false);
                          panel1.setBackground(Color.red);
                          
                          cevap2.setEnabled(false);
                          cevapla2.setEnabled(false);
                          panel2.setBackground(Color.red);
                          
                          cevap3.setEnabled(false);
                          cevapla3.setEnabled(false);
                          panel3.setBackground(Color.red);
                      
                      if((key1basildimi || key2basildimi || key3basildimi) && hatali_cevap_sayisi <= 1/* &&sayac_yarismacicevap < 2*/)
                      {
                          System.out.println(hatali_cevap_sayisi);
                          hatali_cevap_sayisi = hatali_cevap_sayisi + 1;
                        //  sayac_yarismacicevap = sayac_yarismacicevap + 1;
                         
                          sayac = sayac_baslangic;
                          key1basildimi = false;
                          key2basildimi = false;
                          key3basildimi = false;
                          basipcevaplamazsapuandus();
                          
                          
                      }
                      else
                      {
                          zamanlayici.stop();
                          if(okunan_soru_sayisi == 25)
                             sonrakietap();
                          else
                          {
                          sorulabel.setText("Tablodan yeni bir soru seçin.(Soru Seçecek Yarışmacı: " + soru_sececek_yarismaci+ " )");
                          zamanlabel.setText("Süre doldu.Cevap: " + cevap);
                          }
                      }
                  }
                      
                      
                      
                  
                }
                
                
        
        });
    
    
    private Statement baglantiAc()throws Exception{
    
         Class.forName("com.mysql.jdbc.Driver");
            
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/briskveritabani?useUnicode=true&charecterEncoding=utf8","root", "123456");
            return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
    }
    private void baglantiKapat()throws Exception{
        conn.close();
    }
    
    
    
   private void sonrakietap(){
       
       sorulabel.setText("");
       zamanlabel.setText("");
       JOptionPane.showMessageDialog(null,"1.ETAP BİTTİ.2.ETAP BAŞLAYACAK");
       Etap2 etp2 = new Etap2();
       etp2.setVisible(true);
       this.hide();
   }
   
   private void soruSec(int kategoriid,int spuan)
   {
       try{
            st = baglantiAc();
            veri = st.executeQuery("SELECT Soru, Cevap FROM sorular WHERE KategoriID = '" + kategoriid + "' and Puan = '"+ spuan + "'" );
            veri.next();
            sorulabel.setText(veri.getString(1));
            cevap = veri.getString(2);
            baglantiKapat();
            puan = spuan;
            hatali_cevap_sayisi= 0;
            sayac = sayac_baslangic;
            zamanlayici.start();
            //sayac_yarismacicevap = 0;
            key1basildimi = false; key2basildimi = false; key3basildimi = false; key1ilkmi = true;  key2ilkmi = true; key3ilkmi = true; sorusecildimi = true;
            okunan_soru_sayisi = okunan_soru_sayisi + 1;
            
        }catch(Exception ex){
            System.out.println("Hata");
            ex.printStackTrace();
        }
                      
       
   }
   private void cevapla(JLabel isimlabel,JTextField cevaptext,JLabel puanlabel,int kisiid,ActionEvent ev)
   {
        zamanlayici.stop();
        zamanlabel.setText("");
       
       
            try
            {
                 st = baglantiAc();
                 if (cevaptext.getText().equals(cevap))
                 {
                   JOptionPane.showMessageDialog(null, "DOĞRU CEVAP " + isimlabel.getText() + " "+ Integer.toString(puan) + " PUAN KAZANDI");
                   st.executeUpdate("UPDATE yarismacilar SET Puan = Puan + '" + puan + "' WHERE KisiID = '"+ kisiid +"'");
                    if(okunan_soru_sayisi == 25) 
                              sonrakietap();          
                    else
                    {
                   soru_sececek_yarismaci = isimlabel.getText();
                   sorulabel.setText("Tablodan yeni bir soru seçin.(Soru Seçecek Yarışmacı: " + soru_sececek_yarismaci+ " )");
                    }
                   
                 }
                 else
                 {
                   JOptionPane.showMessageDialog(null,"YANLIŞ CEVAP " + isimlabel.getText() + " " + Integer.toString(puan) + " PUAN KAYBETTİ" );
                   st.executeUpdate("UPDATE yarismacilar SET Puan = Puan - '" + puan +"' WHERE KisiID = '"+ kisiid +"'");
                   hatali_cevap_sayisi = hatali_cevap_sayisi + 1;
                   System.out.println(hatali_cevap_sayisi);
                   if (hatali_cevap_sayisi == 3)
                   {
                       if(okunan_soru_sayisi == 25)
                           sonrakietap(); 
                       else
                       {
                       hatali_cevap_sayisi= 0;
                       zamanlabel.setText("Kimse cevap veremedi.Cevap: "  + cevap);
                       }
                   }
                   else
                   {
                      sayac = sayac_baslangic;
                      zamanlayici.start();
                      
                   }
                   
                   Object source = ev.getSource();
                   if( source == cevapla1)
                     key1basildimi = false;
                   else if(source == cevapla2)
                     key2basildimi = false;
                   else if(source == cevapla3)
                     key3basildimi = false;
                 }
                 
                  veri = st.executeQuery("SELECT Puan FROM yarismacilar WHERE KisiID = '"+ kisiid +"'");
                  veri.next();
                  puanlabel.setText("PUAN: " + veri.getString(1));
                  baglantiKapat();
                 
            }catch( Exception e)
            {
                System.out.println("Hata oluştu");
                
            }
            
            cevaptext.setText("");
   }
        
   private void basipcevaplamazsapuandus()
   {
       try
       {
           st = baglantiAc(); 
           st.executeUpdate("UPDATE yarismacilar SET Puan = Puan - '" + puan +"' WHERE KisiID = '" + basilanbuton + "'");
           veri = st.executeQuery("SELECT Puan FROM yarismacilar WHERE KisiID = '" + basilanbuton + "'");
           veri.next();
           if(basilanbuton == 1)
               puan1.setText("PUAN: " + veri.getString(1));
           if(basilanbuton == 2)
               puan2.setText("PUAN " + veri.getString(1));
           if(basilanbuton == 3)
               puan3.setText("PUAN: " + veri.getString(1));
           baglantiKapat();
       }catch (Exception e) {
           System.out.println("Veritabanı Hatası");
       }
               
   }
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
            try {
                st = baglantiAc();
                st.execute("DELETE FROM yarismacilar");
                baglantiKapat();
            } catch (Exception ex) {
                Logger.getLogger(Etap1.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Baglanti Basarisiz");
            }
            
       
    }//GEN-LAST:event_formWindowClosing

    
    private void buton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton11ActionPerformed
        // TODO add your handling code here:
       soruSec(1,100);
       buton11.setVisible(false);
    }//GEN-LAST:event_buton11ActionPerformed

    private void cevapla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cevapla1ActionPerformed
        // TODO add your handling code here:
        cevap1.setEnabled(false);
        cevapla1.setEnabled(false);
        panel1.setBackground(Color.red);
        cevapla(isim1,cevap1,puan1,1,evt);
        
        
    }//GEN-LAST:event_cevapla1ActionPerformed

    private void resimPaneli21KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resimPaneli21KeyPressed
        // TODO add your handling code here:
      if (sorusecildimi && sayac > 0)
      {
        switch(evt.getKeyCode())
        {
            case KeyEvent.VK_NUMPAD1: 
                if (!key2basildimi && !key3basildimi && key1ilkmi)
                {
                    panel1.setBackground(Color.green);
                    cevap1.setEnabled(true);
                    cevapla1.setEnabled(true);
                    key1basildimi = true;
                    key1ilkmi = false;
                    sayac = sayac_baslangic;
                    basilanbuton = 1;
                }
                break; 
            case KeyEvent.VK_NUMPAD2 :
                 if (!key1basildimi && !key3basildimi && key2ilkmi)
                {
                    panel2.setBackground(Color.green);
                    cevap2.setEnabled(true);
                    cevapla2.setEnabled(true);
                    key2basildimi = true;
                    key2ilkmi = false;
                    sayac = sayac_baslangic;
                    basilanbuton = 2;
                }
                break;
            
              case KeyEvent.VK_NUMPAD3 :
                 if (!key1basildimi && !key2basildimi && key3ilkmi)
                {
                    panel3.setBackground(Color.green);
                    cevap3.setEnabled(true);
                    cevapla3.setEnabled(true);
                    key3basildimi = true;
                    key3ilkmi = false;
                    sayac = sayac_baslangic;
                    basilanbuton = 3;
                }
                break;  
                
              default : keyChar = evt.getKeyChar();
                
        }
      }
        
    }//GEN-LAST:event_resimPaneli21KeyPressed

    private void buton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton12ActionPerformed
        // TODO add your handling code here:
       soruSec(1,200);
       buton12.setVisible(false);
        
    }//GEN-LAST:event_buton12ActionPerformed

    private void buton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton13ActionPerformed
        // TODO add your handling code here:
       soruSec(1,300);
       buton13.setVisible(false);
    }//GEN-LAST:event_buton13ActionPerformed

    private void cevapla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cevapla2ActionPerformed
        // TODO add your handling code here:
        cevap2.setEnabled(false);
        cevapla2.setEnabled(false);
        panel2.setBackground(Color.red);
        cevapla(isim2,cevap2,puan2,2,evt);
    }//GEN-LAST:event_cevapla2ActionPerformed

    private void cevapla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cevapla3ActionPerformed
        // TODO add your handling code here:
        cevap3.setEnabled(false);
        cevapla3.setEnabled(false);
        panel3.setBackground(Color.red);
        cevapla(isim3,cevap3,puan3,3,evt);
        
        
    }//GEN-LAST:event_cevapla3ActionPerformed

    private void buton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton14ActionPerformed
        // TODO add your handling code here:
       soruSec(1,400);
       buton14.setVisible(false);
    }//GEN-LAST:event_buton14ActionPerformed

    private void buton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton15ActionPerformed
        // TODO add your handling code here:
       soruSec(1,500);
       buton15.setVisible(false);
    }//GEN-LAST:event_buton15ActionPerformed

    private void buton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton21ActionPerformed
        // TODO add your handling code here:
       soruSec(2,100);
       buton21.setVisible(false);
    }//GEN-LAST:event_buton21ActionPerformed

    private void buton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton22ActionPerformed
        // TODO add your handling code here:
       soruSec(2,200);
       buton22.setVisible(false);
    }//GEN-LAST:event_buton22ActionPerformed

    private void buton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton23ActionPerformed
        // TODO add your handling code here:
       soruSec(2,300);
       buton23.setVisible(false);
    }//GEN-LAST:event_buton23ActionPerformed

    private void buton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton24ActionPerformed
        // TODO add your handling code here:
       soruSec(2,400);
       buton24.setVisible(false);
    }//GEN-LAST:event_buton24ActionPerformed

    private void buton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton25ActionPerformed
        // TODO add your handling code here:
       soruSec(2,500);
       buton25.setVisible(false);
    }//GEN-LAST:event_buton25ActionPerformed

    private void buton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton31ActionPerformed
        // TODO add your handling code here:
       soruSec(3,100);
       buton31.setVisible(false);
    }//GEN-LAST:event_buton31ActionPerformed

    private void buton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton32ActionPerformed
        // TODO add your handling code here:
        soruSec(3,200);
       buton32.setVisible(false);
    }//GEN-LAST:event_buton32ActionPerformed

    private void buton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton33ActionPerformed
        // TODO add your handling code here:
        soruSec(3,300);
       buton33.setVisible(false);
    }//GEN-LAST:event_buton33ActionPerformed

    private void buton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton34ActionPerformed
        // TODO add your handling code here:
       soruSec(3,400);
       buton34.setVisible(false);
    }//GEN-LAST:event_buton34ActionPerformed

    private void buton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton35ActionPerformed
        // TODO add your handling code here:
       soruSec(3,500);
       buton35.setVisible(false);
    }//GEN-LAST:event_buton35ActionPerformed

    private void buton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton41ActionPerformed
        // TODO add your handling code here:
       soruSec(4,100);
       buton41.setVisible(false);
    }//GEN-LAST:event_buton41ActionPerformed

    private void buton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton42ActionPerformed
        // TODO add your handling code here:
       soruSec(4,200);
       buton42.setVisible(false);
    }//GEN-LAST:event_buton42ActionPerformed

    private void buton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton43ActionPerformed
        // TODO add your handling code here:
       soruSec(4,300);
       buton43.setVisible(false);
    }//GEN-LAST:event_buton43ActionPerformed

    private void buton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton44ActionPerformed
        // TODO add your handling code here:
       soruSec(4,400);
       buton44.setVisible(false);
    }//GEN-LAST:event_buton44ActionPerformed

    private void buton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton45ActionPerformed
        // TODO add your handling code here:
       soruSec(4,500);
       buton45.setVisible(false);
    }//GEN-LAST:event_buton45ActionPerformed

    private void buton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton51ActionPerformed
        // TODO add your handling code here:
       soruSec(5,100);
       buton51.setVisible(false);
    }//GEN-LAST:event_buton51ActionPerformed

    private void buton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton52ActionPerformed
        // TODO add your handling code here:
       soruSec(5,200);
       buton52.setVisible(false);
    }//GEN-LAST:event_buton52ActionPerformed

    private void buton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton53ActionPerformed
        // TODO add your handling code here:
       soruSec(5,300);
       buton53.setVisible(false);
    }//GEN-LAST:event_buton53ActionPerformed

    private void buton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton54ActionPerformed
        // TODO add your handling code here:
       soruSec(5,400);
       buton54.setVisible(false);
    }//GEN-LAST:event_buton54ActionPerformed

    private void buton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton55ActionPerformed
        // TODO add your handling code here:
       soruSec(5,500);
       buton55.setVisible(false);
    }//GEN-LAST:event_buton55ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Etap1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Etap1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Etap1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Etap1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etap1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton11;
    private javax.swing.JButton buton12;
    private javax.swing.JButton buton13;
    private javax.swing.JButton buton14;
    private javax.swing.JButton buton15;
    private javax.swing.JButton buton21;
    private javax.swing.JButton buton22;
    private javax.swing.JButton buton23;
    private javax.swing.JButton buton24;
    private javax.swing.JButton buton25;
    private javax.swing.JButton buton31;
    private javax.swing.JButton buton32;
    private javax.swing.JButton buton33;
    private javax.swing.JButton buton34;
    private javax.swing.JButton buton35;
    private javax.swing.JButton buton41;
    private javax.swing.JButton buton42;
    private javax.swing.JButton buton43;
    private javax.swing.JButton buton44;
    private javax.swing.JButton buton45;
    private javax.swing.JButton buton51;
    private javax.swing.JButton buton52;
    private javax.swing.JButton buton53;
    private javax.swing.JButton buton54;
    private javax.swing.JButton buton55;
    private javax.swing.JTextField cevap1;
    private javax.swing.JTextField cevap2;
    private javax.swing.JTextField cevap3;
    private javax.swing.JButton cevapla1;
    private javax.swing.JButton cevapla2;
    private javax.swing.JButton cevapla3;
    private javax.swing.JLabel isim1;
    private javax.swing.JLabel isim2;
    private javax.swing.JLabel isim3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JLabel puan1;
    private javax.swing.JLabel puan2;
    private javax.swing.JLabel puan3;
    private buyukrisk.ResimPaneli2 resimPaneli21;
    private javax.swing.JLabel sorulabel;
    private javax.swing.JLabel zamanlabel;
    // End of variables declaration//GEN-END:variables
}
