/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buyukrisk;

import com.mysql.jdbc.Connection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author TOSHIBA S70
 */
public class Final extends javax.swing.JFrame {

    /**
     * Creates new form Final
     */
    public Final() {
        initComponents();
        setLocationRelativeTo(null);
        Random rnd = new Random();
        deger = rnd.nextInt(2) + 51;
        sorupanel.setVisible(false);
        if (deger == 51)
            baslikbuton.setText("TAVUK");
        else if (deger == 52)
            baslikbuton.setText("2013");
        else if (deger == 53)
            baslikbuton.setText("PARA");
        
        try {
         st = baglantiAc();
         veri = st.executeQuery("SELECT Ad,Puan FROM yarismacilar");
         veri.next();
         isim1.setText(veri.getString(1));
         puan1.setText("PUAN: " + veri.getString(2));
         veri.next();
         isim2.setText(veri.getString(1));
         puan2.setText( "PUAN: " + veri.getString(2));
         veri.next();
         isim3.setText(veri.getString(1));
         puan3.setText("PUAN: " + veri.getString(2));
         
         baglantiKapat();
        
        
        }catch(Exception e){
            System.out.println("Veitabanı bağlantı hatası");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resimPaneli21 = new buyukrisk.ResimPaneli2();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        baslikbuton = new javax.swing.JButton();
        sorupanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sorulabel = new javax.swing.JLabel();
        zamanlabel = new javax.swing.JLabel();
        puan3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        isim3 = new javax.swing.JLabel();
        puan1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        isim2 = new javax.swing.JLabel();
        puan2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        isim1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cevap1 = new javax.swing.JTextField();
        cevap2 = new javax.swing.JTextField();
        cevapver3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        risk1 = new javax.swing.JTextField();
        cevap3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cevapver1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        risk2 = new javax.swing.JTextField();
        risk3 = new javax.swing.JTextField();
        cevapver2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        resimPaneli21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FİNAL KONU BAŞLIĞI");
        resimPaneli21.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("------Final Etabına Hoşgeldiniz-----");
        resimPaneli21.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        baslikbuton.setBackground(new java.awt.Color(255, 102, 0));
        baslikbuton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        baslikbuton.setForeground(new java.awt.Color(255, 255, 255));
        baslikbuton.setText("OSMANLI");
        baslikbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslikbutonActionPerformed(evt);
            }
        });
        resimPaneli21.add(baslikbuton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 400, 160));

        sorupanel.setBackground(new java.awt.Color(0, 51, 153));
        sorupanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("-----------------------------------------------------------------------------FİNAL SORUSU---------------------------------------------------------------------------");
        sorupanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1360, -1));

        sorulabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sorulabel.setForeground(new java.awt.Color(255, 255, 255));
        sorulabel.setText("DSDSDSDSDSDSD DSDA");
        sorupanel.add(sorulabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        zamanlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        zamanlabel.setForeground(new java.awt.Color(255, 102, 0));
        zamanlabel.setText("kalan süre :  ");
        sorupanel.add(zamanlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 170, 30));

        resimPaneli21.add(sorupanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 1350, 160));

        puan3.setBackground(new java.awt.Color(0, 0, 153));
        puan3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        puan3.setForeground(new java.awt.Color(255, 255, 255));
        puan3.setText("PUAN:");
        resimPaneli21.add(puan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 470, 170, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 153));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("______________");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        resimPaneli21.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 500, 330, 10));

        isim3.setBackground(new java.awt.Color(0, 0, 153));
        isim3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        isim3.setForeground(new java.awt.Color(0, 0, 153));
        isim3.setText("AHMET");
        resimPaneli21.add(isim3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 470, -1, -1));

        puan1.setBackground(new java.awt.Color(0, 0, 153));
        puan1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        puan1.setForeground(new java.awt.Color(255, 255, 255));
        puan1.setText("PUAN:");
        resimPaneli21.add(puan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 170, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 153));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText("______________");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        resimPaneli21.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 330, 10));

        isim2.setBackground(new java.awt.Color(0, 0, 153));
        isim2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        isim2.setForeground(new java.awt.Color(0, 0, 153));
        isim2.setText("AHMET");
        resimPaneli21.add(isim2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));

        puan2.setBackground(new java.awt.Color(0, 0, 153));
        puan2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        puan2.setForeground(new java.awt.Color(255, 255, 255));
        puan2.setText("PUAN:");
        resimPaneli21.add(puan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 170, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 153));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 51));
        jLabel13.setText("______________");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        resimPaneli21.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 330, 10));

        isim1.setBackground(new java.awt.Color(0, 0, 153));
        isim1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        isim1.setForeground(new java.awt.Color(0, 0, 153));
        isim1.setText("AHMET");
        resimPaneli21.add(isim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        jLabel15.setBackground(new java.awt.Color(0, 0, 153));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("Cevap:");
        resimPaneli21.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 580, -1, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 153));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("Risk Miktarı:");
        resimPaneli21.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 520, -1, -1));

        cevap1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cevap1.setEnabled(false);
        resimPaneli21.add(cevap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 200, 40));

        cevap2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cevap2.setEnabled(false);
        resimPaneli21.add(cevap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 200, 40));

        cevapver3.setBackground(new java.awt.Color(255, 102, 0));
        cevapver3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cevapver3.setForeground(new java.awt.Color(255, 255, 255));
        cevapver3.setText("CEVAP VER");
        cevapver3.setEnabled(false);
        cevapver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cevapver3ActionPerformed(evt);
            }
        });
        resimPaneli21.add(cevapver3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 650, 220, 50));

        jLabel17.setBackground(new java.awt.Color(0, 0, 153));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("Risk Miktarı:");
        resimPaneli21.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, -1));

        risk1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        risk1.setEnabled(false);
        resimPaneli21.add(risk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 200, 40));

        cevap3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cevap3.setEnabled(false);
        resimPaneli21.add(cevap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 580, 200, 40));

        jLabel18.setBackground(new java.awt.Color(0, 0, 153));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("Cevap:");
        resimPaneli21.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, -1, -1));

        cevapver1.setBackground(new java.awt.Color(255, 102, 0));
        cevapver1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cevapver1.setForeground(new java.awt.Color(255, 255, 255));
        cevapver1.setText("CEVAP VER");
        cevapver1.setEnabled(false);
        cevapver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cevapver1ActionPerformed(evt);
            }
        });
        resimPaneli21.add(cevapver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 650, 220, 50));

        jLabel19.setBackground(new java.awt.Color(0, 0, 153));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("Risk Miktarı:");
        resimPaneli21.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, -1, -1));

        jLabel20.setBackground(new java.awt.Color(0, 0, 153));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 0));
        jLabel20.setText("Cevap:");
        resimPaneli21.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, -1, -1));

        risk2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        risk2.setEnabled(false);
        resimPaneli21.add(risk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 200, 40));

        risk3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        risk3.setEnabled(false);
        resimPaneli21.add(risk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 520, 200, 40));

        cevapver2.setBackground(new java.awt.Color(255, 102, 0));
        cevapver2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cevapver2.setForeground(new java.awt.Color(255, 255, 255));
        cevapver2.setText("CEVAP VER");
        cevapver2.setEnabled(false);
        cevapver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cevapver2ActionPerformed(evt);
            }
        });
        resimPaneli21.add(cevapver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 650, 220, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resimPaneli21, javax.swing.GroupLayout.DEFAULT_SIZE, 1704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resimPaneli21, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baslikbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslikbutonActionPerformed
        // TODO add your handling code here:
          try{
            st = baglantiAc();
            veri = st.executeQuery("SELECT Soru,Cevap FROM sorular WHERE SoruID = '" + deger + "'");
            veri.next();
            sorulabel.setText(veri.getString(1));
            cevap = veri.getString(2);
            baglantiKapat();
            sorupanel.setVisible(true);
            risk1.setEnabled(true);
            risk2.setEnabled(true);
            risk3.setEnabled(true);
            cevap1.setEnabled(true);
            cevap2.setEnabled(true);
            cevap3.setEnabled(true);
            cevapver1.setEnabled(true);
            cevapver2.setEnabled(true);
           cevapver3.setEnabled(true);
                
            
            zamanlayici.start();
          
            
        }catch (Exception e){
            System.out.println("Veritabani hatasi");
        }
                
    }//GEN-LAST:event_baslikbutonActionPerformed

    private void cevapver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cevapver1ActionPerformed
        // TODO add your handling code here:
         spuan1 = puanDondur(1);
        cevapVer(risk1,cevap1,spuan1);
    }//GEN-LAST:event_cevapver1ActionPerformed

    private void cevapver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cevapver2ActionPerformed
        // TODO add your handling code here:
        spuan2 = puanDondur(2);
        cevapVer(risk2,cevap2,spuan2);
    }//GEN-LAST:event_cevapver2ActionPerformed

    private void cevapver3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cevapver3ActionPerformed
        // TODO add your handling code here:
        spuan3 = puanDondur(3);
        cevapVer(risk3,cevap3,spuan3);
    }//GEN-LAST:event_cevapver3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         try {
                st = baglantiAc();
                st.execute("DELETE FROM yarismacilar");
                baglantiKapat();
            } catch (Exception ex) {
                Logger.getLogger(Final.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Baglanti Basarisiz");
            }
    }//GEN-LAST:event_formWindowClosing
    Connection conn = null;
    ResultSet veri;
    Statement st;
    String cevap;
    int deger = 0,sayac = 40,y1toplampuan = 0,y2toplampuan = 0,y3toplampuan = 0,spuan1,spuan2,spuan3;
    
    Timer zamanlayici = new Timer(1000, new ActionListener(){
        
         @Override
         public void actionPerformed(ActionEvent e)
         {
             sayac = sayac - 1;
             zamanlabel.setText(" Kalan Süre: " + Integer.toString(sayac));
             
             if (sayac == 0)
             {
                 risk1.setEnabled(false);
                 risk2.setEnabled(false);
                 risk3.setEnabled(false);
                 cevap1.setEnabled(false);
                 cevap2.setEnabled(false);
                 cevap3.setEnabled(false);
                 cevapver1.setEnabled(false);
                 cevapver2.setEnabled(false);
                 cevapver3.setEnabled(false);
                
                 zamanlayici.stop();
                 
                 IslemleriYap();
             }
             
         }
    });
    
     private Statement baglantiAc()throws Exception{
    
         Class.forName("com.mysql.jdbc.Driver");
            
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/briskveritabani?useUnicode=true&charecterEncoding=utf8","root", "123456");
            return conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
    }
    private void baglantiKapat()throws Exception{
        conn.close();
    }
    
    private void cevapVer( JTextField risk,JTextField cevap,int puan)
    {
       int  risks = Integer.parseInt(risk.getText());
       if (puan <= 1000 && risks > 1000)
           JOptionPane.showMessageDialog(null,"1000 PUANDAN FAZLA RİSKE EDEMEZSİNİZ");
       else if ( puan > 1000 && risks > puan)
           JOptionPane.showMessageDialog(null,"KENDİ PUANINIZDAN FAZLA RİSKE EDEMEZSİNİZ");
       else
       {
           risk.setEnabled(false);
           cevap.setEnabled(false);
       }
    }
    
    private void  IslemleriYap()
    {
         int  risks1 = Integer.parseInt(risk1.getText());
          int  risks2 = Integer.parseInt(risk2.getText());
           int  risks3 = Integer.parseInt(risk3.getText());
           
           
         
       if (cevap1.getText().equals(cevap))
          y1toplampuan = spuan1 + risks1;
       else
          y1toplampuan = spuan1 - risks1;
       
       if (cevap2.getText().equals(cevap))
          y2toplampuan = spuan2+ risks2;
       else
          y2toplampuan = spuan2 - risks2;
       
        if (cevap3.getText().equals(cevap))
          y3toplampuan = spuan3 +risks3;
       else
          y3toplampuan = spuan3 - risks3;
        
        puan1.setText(Integer.toString(y1toplampuan));
        puan2.setText(Integer.toString(y2toplampuan));
        puan3.setText(Integer.toString(y3toplampuan));
        
        if(y1toplampuan > y2toplampuan && y1toplampuan > y3toplampuan)
            sorulabel.setText("KAZANAN: " + isim1.getText());
        else if(y2toplampuan > y1toplampuan && y2toplampuan > y3toplampuan)
            sorulabel.setText("KAZANAN: " + isim2.getText());
        else if(y3toplampuan > y2toplampuan && y3toplampuan > y1toplampuan)
            sorulabel.setText("KAZANAN: " + isim1.getText());
        else if ( y1toplampuan == y2toplampuan && y1toplampuan  == y3toplampuan)
            sorulabel.setText("ÜÇ YARIŞMACIDA BERABERE");
        else
            sorulabel.setText("İKİ YARIŞMACI BERABERE");
    }
    
    private int  puanDondur(int kisiid)
    {
        int puan = 0;
        try
        {
            st=baglantiAc();
            veri = st.executeQuery("select Puan from yarismacilar where KisiID = '"+kisiid+"'");
            veri.next();
            puan = veri.getInt(1);
            baglantiKapat();
            
        }catch (Exception e)
        {
            
        }
        return puan;     
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baslikbuton;
    private javax.swing.JTextField cevap1;
    private javax.swing.JTextField cevap2;
    private javax.swing.JTextField cevap3;
    private javax.swing.JButton cevapver1;
    private javax.swing.JButton cevapver2;
    private javax.swing.JButton cevapver3;
    private javax.swing.JLabel isim1;
    private javax.swing.JLabel isim2;
    private javax.swing.JLabel isim3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel puan1;
    private javax.swing.JLabel puan2;
    private javax.swing.JLabel puan3;
    private buyukrisk.ResimPaneli2 resimPaneli21;
    private javax.swing.JTextField risk1;
    private javax.swing.JTextField risk2;
    private javax.swing.JTextField risk3;
    private javax.swing.JLabel sorulabel;
    private javax.swing.JPanel sorupanel;
    private javax.swing.JLabel zamanlabel;
    // End of variables declaration//GEN-END:variables
}
